version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: rocketseat-prompt-manager-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: rocketseat_prompt_manager

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: